arr = list(map(float, input("Введите элементы массива: ").split()))
max_val = max(arr)
arr_copy = arr.copy()
arr_copy.remove(max_val)
second_max = max(arr_copy)
print(f"а) Максимальный элемент: {max_val}, следующий по величине: {second_max}")
min_val = min(arr)
arr_copy = arr.copy()
arr_copy.remove(min_val)
second_min = min(arr_copy)
print(f"б) Минимальный элемент: {min_val}, следующий по малости: {second_min}")
max_index = arr.index(max_val)
second_max_index = arr.index(second_max)
print(f"в) Номер максимального элемента: {max_index}, следующего по величине: {second_max_index}")
min_index = arr.index(min_val)
second_min_index = arr.index(second_min)
print(f"г) Номер минимального элемента: {min_index}, следующего по малости: {second_min_index}")